// ai前端/example/packages/editor-vue3/src/App.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const props = defineProps({
  shellProps: { type: Object, default: () => ({}) },
});

const modelId = ref('-');
const sessionId = ref('（等待 Chat 广播）');
const text = ref("function hello() { return 'world'; }");
const unsubs = [];

onMounted(() => {
  const { globalStore, eventBus } = props.shellProps;
  if (globalStore) {
    unsubs.push(globalStore.subscribe((s) => { modelId.value = s.modelId; }));
  }
  if (eventBus) {
    unsubs.push(eventBus.on('ai:session:changed', (p) => { sessionId.value = p.sessionId; }));
  }
});

onUnmounted(() => {
  unsubs.forEach((fn) => fn && fn());
});

function emitSelection() {
  const { eventBus } = props.shellProps;
  eventBus?.emit('editor:selection', { text: text.value.slice(0, 40) + '…' });
}
</script>

<template>
  <div class="subapp subapp-editor">
    <h2>📝 Editor · Vue 3</h2>
    <p class="subapp-meta">qiankun 子应用 editor-vue3 · 独立端口 7102</p>
    <p>当前模型：<strong>{{ modelId }}</strong></p>
    <p>会话 ID：<code>{{ sessionId }}</code></p>
    <textarea v-model="text" style="width: 100%; height: 80px" />
    <button type="button" @click="emitSelection">模拟：将选区发给 Chat</button>
  </div>
</template>

// ai前端/example/packages/viz-react/src/App.jsx
import { useEffect, useState } from 'react';

export default function App({ shellProps = {} }) {
  const [modelId, setModelId] = useState('-');
  const [events, setEvents] = useState([]);

  useEffect(() => {
    const { globalStore, eventBus } = shellProps;
    const unsubs = [];

    if (globalStore) {
      unsubs.push(globalStore.subscribe((s) => setModelId(s.modelId)));
    }
    if (eventBus) {
      const push = (kind) => (payload) => {
        setEvents((prev) => [`[${kind}] ${JSON.stringify(payload)}`, ...prev].slice(0, 8));
      };
      unsubs.push(eventBus.on('ai:session:changed', push('session')));
      unsubs.push(eventBus.on('ai:model:changed', push('model')));
      unsubs.push(eventBus.on('editor:selection', push('selection')));
    }

    return () => unsubs.forEach((fn) => fn && fn());
  }, [shellProps]);

  return (
    <div className="subapp subapp-viz">
      <h2>📊 Viz · React</h2>
      <p className="subapp-meta">qiankun 子应用 viz-react · 独立端口 7103</p>
      <p>
        当前模型：<strong>{modelId}</strong>
      </p>
      <p>监听到的事件：</p>
      <ul className="events">
        {events.length === 0 ? <li>（暂无）</li> : events.map((e, i) => <li key={i}>{e}</li>)}
      </ul>
    </div>
  );
}
